package it.polito.wa2.g05.server.purchases.entities

import it.polito.wa2.g05.server.products.entities.Product
import it.polito.wa2.g05.server.profiles.entities.Profile
import it.polito.wa2.g05.server.specializations.entities.Specialization
import it.polito.wa2.g05.server.utils.AutoGeneratedUUIDEntity
import it.polito.wa2.g05.server.utils.SerialIdEntity
import jakarta.persistence.*
import java.io.Serializable
import java.util.Date
import java.util.UUID

@Entity
@Table(name = "purchases")
class Purchase(
    @ManyToOne
    @JoinColumn(name = "profile_id", referencedColumnName = "id")
    var profile: Profile? = null,

    @Column(name = "purchased_at")
    var purchasedAt: Date,


    @ManyToMany
    @JoinTable(
        name = "purchase_product",
        joinColumns = [JoinColumn(name = "purchase_id")],
        inverseJoinColumns = [JoinColumn(name = "product_id")]
    )
    var products: MutableSet<Product> = mutableSetOf()
) : AutoGeneratedUUIDEntity()