package it.polito.wa2.g05.server.utils

import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import java.util.*

abstract class AutoGeneratedUUIDEntity (
    @Id @GeneratedValue(strategy = GenerationType.UUID)
    override var id: UUID? = null
): EntityBase<UUID>()