package it.polito.wa2.g05.server.notifications.entities

import it.polito.wa2.g05.server.utils.AutoGeneratedUUIDEntity
import jakarta.persistence.Entity
import jakarta.persistence.Table
import java.util.Date
import java.util.UUID

@Entity
@Table(name = "notifications")
class Notification (
    var text: String,
    var receiver: UUID,
    var timestamp: Date
): AutoGeneratedUUIDEntity()