package it.polito.wa2.g05.server.tickets.entities

import it.polito.wa2.g05.server.utils.AutoGeneratedUUIDEntity
import jakarta.persistence.Entity
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table

@Entity
@Table(name = "attachments")
class Attachment (
    var filename: String,

    @ManyToOne
    @JoinColumn(name="ticket_id" , referencedColumnName = "id")
    var ticket: Ticket,
): AutoGeneratedUUIDEntity()