package it.polito.wa2.g05.server.tickets.entities

import it.polito.wa2.g05.server.utils.AutoGeneratedUUIDEntity
import jakarta.persistence.*
import java.util.*

@Entity
@Table(name = "messages")
class Message (
    var text: String,
    var timestamp: Date,

    @ManyToOne
    @JoinColumn(name="ticket_id" , referencedColumnName = "id")
    var ticket: Ticket,

    @Column(name = "is_from_customer")
    var isFromCustomer: Boolean
): AutoGeneratedUUIDEntity()