version: '2'

services:
  server:
    image: 'gcr.io/g5project-385811/server:latest'
    build:
      context: .
    container_name: g05-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: g05-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password